# Generated by Django 4.2.5 on 2023-09-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram User ID')),
                ('user_lang', models.CharField(blank=True, choices=[('en', 'English'), ('uz', 'Uzbek')], default='en', max_length=2, null=True, verbose_name='User Language')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('user_contact', models.CharField(blank=True, max_length=15, null=True, verbose_name='User Contact')),
                ('user_step', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Registration Step')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('is_fully_registered', models.BooleanField(default=False)),
                ('current_message_to_reply', models.BigIntegerField(blank=True, null=True, verbose_name='Current Message to Reply')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
        migrations.CreateModel(
            name='TelegramAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversations', models.ManyToManyField(blank=True, related_name='admin_conversations', to='botapp.telegramuser')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botapp.telegramuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Telegram Admin',
                'verbose_name_plural': 'Telegram Admins',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='botapp.telegramuser')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.telegramadmin'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.telegramuser'),
        ),
    ]
