# Generated by Django 4.2.5 on 2023-09-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
